services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    networks:
      - front
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    networks:
      - front
    restart: always

networks:
  front:
    driver: bridge
